# Generated by Django 5.1.2 on 2024-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='add',
            field=models.CharField(default='lskdnglskd', max_length=60),
            preserve_default=False,
        ),
    ]
