# Generated by Django 5.1.2 on 2024-10-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_student_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='add',
        ),
    ]
